//    uniCenta oPOS  - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2016 uniCenta
//    http://www.unicenta.com
//    This file is part of uniCenta oPOS
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//   uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.config;

import com.openbravo.data.user.DirtyManager;
import com.openbravo.pos.forms.AppConfig;
import com.openbravo.pos.forms.AppLocal;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import java.awt.Robot;
import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.InputEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
        
/**
 *
 * @author JG uniCenta
 */
public class JPanelConfigSalesScreen extends javax.swing.JPanel implements PanelConfig {
    
    private DirtyManager dirty = new DirtyManager();
    private Icon img;
    
    /** Creates new form JPanelConfigDatabase */
    public JPanelConfigSalesScreen() {   
        initComponents();     
        optDefault.addActionListener(dirty); 
        opt1.addActionListener(dirty);
        opt2.addActionListener(dirty);
        opt3.addActionListener(dirty);  
        opt4.addActionListener(dirty); 
        }
       
    /**
     *
     * @return
     */
    @Override
    public boolean hasChanged() {
        return dirty.isDirty();
    }
    
    /**
     *
     * @return
     */
    @Override
    public Component getConfigComponent() {
        return this;
    }
   
    /**
     *
     * @param config
     */
    @Override
    public void loadProperties(AppConfig config) {         
        optDefault.setSelected(Boolean.parseBoolean(config.getProperty("till.salesdefault")));
        opt1.setSelected(Boolean.parseBoolean(config.getProperty("till.sales1")));
        opt2.setSelected(Boolean.parseBoolean(config.getProperty("till.sales2")));
        opt3.setSelected(Boolean.parseBoolean(config.getProperty("till.sales3")));  
        opt4.setSelected(Boolean.parseBoolean(config.getProperty("till.sales4"))); 
        dirty.setDirty(false); 
        redimensionarImagen(); 
    }
   
    /**
     *
     * @param config
     */
    @Override
    public void saveProperties(AppConfig config) {             
        config.setProperty("till.salesdefault", Boolean.toString(optDefault.isSelected()));
        config.setProperty("till.sales1", Boolean.toString(opt1.isSelected()));
        config.setProperty("till.sales2", Boolean.toString(opt2.isSelected()));
        config.setProperty("till.sales3", Boolean.toString(opt3.isSelected()));
        config.setProperty("till.sales4", Boolean.toString(opt4.isSelected()));
        dirty.setDirty(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        optDefault = new javax.swing.JRadioButton();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 500));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 400));
        jPanel4.setLayout(new java.awt.GridLayout(16, 1));

        buttonGroup1.add(optDefault);
        optDefault.setSelected(true);
        optDefault.setText("Default");
        optDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDefaultActionPerformed(evt);
            }
        });
        jPanel4.add(optDefault);

        buttonGroup1.add(opt1);
        opt1.setText("Opción 1");
        opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1ActionPerformed(evt);
            }
        });
        jPanel4.add(opt1);

        buttonGroup1.add(opt2);
        opt2.setText("Opción 2");
        opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2ActionPerformed(evt);
            }
        });
        jPanel4.add(opt2);

        buttonGroup1.add(opt3);
        opt3.setText("Opción 3");
        opt3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                opt3StateChanged(evt);
            }
        });
        opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3ActionPerformed(evt);
            }
        });
        jPanel4.add(opt3);

        buttonGroup1.add(opt4);
        opt4.setText("Opción 4");
        opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4ActionPerformed(evt);
            }
        });
        jPanel4.add(opt4);

        add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown
  
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_formMouseClicked

    private void opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3ActionPerformed
        // TODO add your handling code here:
        redimensionarImagen();    
    }//GEN-LAST:event_opt3ActionPerformed

    private void optDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDefaultActionPerformed
        // TODO add your handling code here:
        redimensionarImagen();
    }//GEN-LAST:event_optDefaultActionPerformed

    private void opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1ActionPerformed
        // TODO add your handling code here:
        redimensionarImagen();
    }//GEN-LAST:event_opt1ActionPerformed

    private void opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2ActionPerformed
        // TODO add your handling code here:
        redimensionarImagen();
    }//GEN-LAST:event_opt2ActionPerformed

    private void opt3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_opt3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_opt3StateChanged

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4ActionPerformed
        // TODO add your handling code here:
        redimensionarImagen();
    }//GEN-LAST:event_opt4ActionPerformed
    
    public void redimensionarImagen(){
        if(optDefault.isSelected()){
        //   ImageIcon fot = new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout_default.png"));
        //   Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
           jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout_default.png")));
           this.repaint(); 
        }
        if(opt1.isSelected()){
        //   ImageIcon fot = new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout1.png"));
        //   Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
           jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout1.png")));
           this.repaint(); 
        }
        if(opt2.isSelected()){
        //   ImageIcon fot = new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout2.png"));
        //   Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
           jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout2.png")));
           this.repaint(); 
        }
        if(opt3.isSelected()){
        //   ImageIcon fot = new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout3.png"));
        //   Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
           jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout3.png")));
           this.repaint(); 
        }  
        if(opt4.isSelected()){
        //   ImageIcon fot = new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout3.png"));
        //   Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
           jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/layout4.png")));
           this.repaint(); 
        } 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JRadioButton optDefault;
    // End of variables declaration//GEN-END:variables
    
}
